version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: baymax-postgres
    environment:
      POSTGRES_USER: baymax
      POSTGRES_PASSWORD: baymax
      POSTGRES_DB: baymax
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U baymax"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: baymax-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: baymax-localstack
    environment:
      - SERVICES=s3,dynamodb,ses,sns,kms
      - AWS_DEFAULT_REGION=ap-south-1
      - EDGE_PORT=4566
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baymax-backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://baymax:baymax@postgres:5432/baymax
      - REDIS_URL=redis://redis:6379/0
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=ap-south-1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      localstack:
        condition: service_started
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  localstack_data: